global using AutoFixture;
global using AutoFixture.AutoMoq;
global using AutoFixture.Xunit2;
global using FluentAssertions;
global using FluentValidation;
global using FluentValidation.TestHelper;
global using Moq;
global using UnitTests.Configuration;
global using Xunit;